// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  var LogRef, auth, fireRef;
  $.ajaxSetup({
    cache: true
  });
  $.getScript('//connect.facebook.net/en_US/sdk.js', function() {
    FB.init({
      appId: '109302492423481',
      version: 'v2.0'
    });
    return FB.api('/v2.0/436620656417436/feed', function(response) {
      return console.log(response);
    });
  });
  fireRef = new Firebase('https://northmpls.firebaseio.com/');
  auth = new FirebaseSimpleLogin(fireRef, function(err, user) {
    var userRef;
    if (err) {
      return console.log(err);
    } else if (user) {
      userRef = fireRef.child('user/' + user.uid);
      userRef.set(user);
    } else {
      console.log('user is logged out');
      return auth.login('google', {
        preferRedirect: true
      });
    }
  });
  LogRef = fireRef.child('list_log');
});
